"use client"

import { useState } from "react"
import { Printer } from "lucide-react"

interface QuoteData {
  id: number
  text: string
  author: string
  category: string
}

interface PrintButtonProps {
  quote: QuoteData
}

function buildPrintCanvas(quote: QuoteData): Promise<string> {
  return new Promise((resolve) => {
    const SIZE = 1080
    const canvas = document.createElement("canvas")
    canvas.width = SIZE
    canvas.height = SIZE
    const ctx = canvas.getContext("2d")!

    // Background gradient — purple to pink (matches reference image)
    const bg = ctx.createLinearGradient(0, 0, SIZE, SIZE)
    bg.addColorStop(0, "#2d1b69")
    bg.addColorStop(0.35, "#5b21b6")
    bg.addColorStop(0.7, "#7c3aed")
    bg.addColorStop(1, "#db2777")
    ctx.fillStyle = bg
    ctx.fillRect(0, 0, SIZE, SIZE)

    // Soft radial glow top-right
    const glow = ctx.createRadialGradient(900, 160, 20, 900, 160, 380)
    glow.addColorStop(0, "rgba(236,72,153,0.35)")
    glow.addColorStop(1, "rgba(236,72,153,0)")
    ctx.fillStyle = glow
    ctx.fillRect(0, 0, SIZE, SIZE)

    // App name — top centre
    ctx.fillStyle = "rgba(255,255,255,0.75)"
    ctx.font = "bold 38px Georgia, serif"
    ctx.textAlign = "center"
    ctx.fillText("\u2728 QuoteApp", SIZE / 2, 100)

    // Card
    const cx = 72, cy = 160, cw = SIZE - 144, ch = SIZE - 290, cr = 44
    ctx.fillStyle = "rgba(255,255,255,0.09)"
    ctx.strokeStyle = "rgba(255,255,255,0.15)"
    ctx.lineWidth = 1.5
    ctx.beginPath()
    ctx.moveTo(cx + cr, cy)
    ctx.lineTo(cx + cw - cr, cy)
    ctx.quadraticCurveTo(cx + cw, cy, cx + cw, cy + cr)
    ctx.lineTo(cx + cw, cy + ch - cr)
    ctx.quadraticCurveTo(cx + cw, cy + ch, cx + cw - cr, cy + ch)
    ctx.lineTo(cx + cr, cy + ch)
    ctx.quadraticCurveTo(cx, cy + ch, cx, cy + ch - cr)
    ctx.lineTo(cx, cy + cr)
    ctx.quadraticCurveTo(cx, cy, cx + cr, cy)
    ctx.closePath()
    ctx.fill()
    ctx.stroke()

    // Category badge — centred at top of card
    const badgeW = 200, badgeH = 48, badgeX = SIZE / 2 - badgeW / 2, badgeY = cy + 36
    ctx.fillStyle = "rgba(255,255,255,0.18)"
    ctx.beginPath()
    ctx.roundRect(badgeX, badgeY, badgeW, badgeH, 24)
    ctx.fill()
    ctx.fillStyle = "rgba(255,255,255,0.85)"
    ctx.font = "600 22px Arial, sans-serif"
    ctx.textAlign = "center"
    ctx.fillText(quote.category.toUpperCase(), SIZE / 2, badgeY + 31)

    // Big opening quote mark
    ctx.fillStyle = "rgba(255,255,255,0.12)"
    ctx.font = "bold 180px Georgia, serif"
    ctx.textAlign = "left"
    ctx.fillText("\u201C", cx + 36, cy + 230)

    // Quote text — word-wrapped, italic bold serif, centred
    ctx.fillStyle = "rgba(255,255,255,0.95)"
    ctx.font = "italic bold 46px Georgia, serif"
    ctx.textAlign = "center"
    const maxW = cw - 120
    const words = quote.text.split(" ")
    const lines: string[] = []
    let line = ""
    for (const word of words) {
      const test = line + word + " "
      if (ctx.measureText(test).width > maxW && line) {
        lines.push(line.trim())
        line = word + " "
      } else {
        line = test
      }
    }
    lines.push(line.trim())
    const lineH = 62
    const totalH = lines.length * lineH
    // Centre text vertically in the card, shifted slightly up
    const textStartY = cy + (ch - totalH) / 2 - 10
    lines.forEach((l, i) => ctx.fillText(l, SIZE / 2, textStartY + i * lineH))

    // Author — bottom of card
    ctx.fillStyle = "rgba(255,255,255,0.65)"
    ctx.font = "500 34px Georgia, serif"
    ctx.textAlign = "center"
    ctx.fillText("\u2014 " + quote.author, SIZE / 2, cy + ch - 52)

    // Watermark — below card
    ctx.fillStyle = "rgba(255,255,255,0.35)"
    ctx.font = "24px Arial, sans-serif"
    ctx.textAlign = "center"
    ctx.fillText("Generated by QuoteApp", SIZE / 2, cy + ch + 52)

    resolve(canvas.toDataURL("image/png"))
  })
}

export function PrintButton({ quote }: PrintButtonProps) {
  const [printing, setPrinting] = useState(false)

  const handlePrint = async () => {
    setPrinting(true)
    try {
      const dataUrl = await buildPrintCanvas(quote)
      // Open a new window containing only the square image and trigger print
      const win = window.open("", "_blank")
      if (!win) return
      win.document.write(`
        <!DOCTYPE html>
        <html>
          <head>
            <title>QuoteApp — Print</title>
            <style>
              @page { margin: 0; size: 1080px 1080px; }
              * { margin: 0; padding: 0; box-sizing: border-box; }
              html, body { width: 1080px; height: 1080px; background: #000; display: flex; align-items: center; justify-content: center; }
              img { display: block; width: 1080px; height: 1080px; }
            </style>
          </head>
          <body>
            <img src="${dataUrl}" alt="Quote" />
            <script>window.onload = function(){ window.print(); }<\/script>
          </body>
        </html>
      `)
      win.document.close()
    } finally {
      setPrinting(false)
    }
  }

  return (
    <button
      onClick={handlePrint}
      disabled={printing}
      className="flex items-center justify-center gap-2 rounded-full bg-white/10 px-4 py-2.5 text-xs font-semibold text-white/70 border border-white/20 transition-all hover:bg-white/20 active:scale-95 min-h-[44px]"
      aria-label="Print quote as square image"
    >
      <Printer className="h-4 w-4" aria-hidden="true" />
      {printing ? "..." : "Print"}
    </button>
  )
}
