"use client"

import { useState } from "react"
import { Download, Share2, Check } from "lucide-react"

interface QuoteData {
  id: number
  text: string
  author: string
  category: string
}

interface ShareButtonsProps {
  quote: QuoteData
  onShare?: () => void
}

function drawQuoteImage(quote: QuoteData): Promise<string> {
  return new Promise((resolve) => {
    const canvas = document.createElement("canvas")
    canvas.width = 1080
    canvas.height = 1080

    const ctx = canvas.getContext("2d")!

    // Background gradient
    const gradient = ctx.createLinearGradient(0, 0, 1080, 1080)
    gradient.addColorStop(0, "#1e1b4b")
    gradient.addColorStop(0.4, "#4c1d95")
    gradient.addColorStop(0.7, "#7c3aed")
    gradient.addColorStop(1, "#db2777")
    ctx.fillStyle = gradient
    ctx.fillRect(0, 0, 1080, 1080)

    // Subtle overlay circle top-right
    const radGrad1 = ctx.createRadialGradient(950, 130, 10, 950, 130, 340)
    radGrad1.addColorStop(0, "rgba(236,72,153,0.3)")
    radGrad1.addColorStop(1, "rgba(236,72,153,0)")
    ctx.fillStyle = radGrad1
    ctx.fillRect(0, 0, 1080, 1080)

    // Card background
    ctx.fillStyle = "rgba(255,255,255,0.08)"
    const cardX = 80
    const cardY = 180
    const cardW = 920
    const cardH = 720
    const r = 40
    ctx.beginPath()
    ctx.moveTo(cardX + r, cardY)
    ctx.lineTo(cardX + cardW - r, cardY)
    ctx.quadraticCurveTo(cardX + cardW, cardY, cardX + cardW, cardY + r)
    ctx.lineTo(cardX + cardW, cardY + cardH - r)
    ctx.quadraticCurveTo(cardX + cardW, cardY + cardH, cardX + cardW - r, cardY + cardH)
    ctx.lineTo(cardX + r, cardY + cardH)
    ctx.quadraticCurveTo(cardX, cardY + cardH, cardX, cardY + cardH - r)
    ctx.lineTo(cardX, cardY + r)
    ctx.quadraticCurveTo(cardX, cardY, cardX + r, cardY)
    ctx.closePath()
    ctx.fill()

    // App name top
    ctx.fillStyle = "rgba(255,255,255,0.6)"
    ctx.font = "bold 36px Georgia, serif"
    ctx.textAlign = "center"
    ctx.fillText("✨ QuoteApp", 540, 120)

    // Quote mark
    ctx.fillStyle = "rgba(255,255,255,0.15)"
    ctx.font = "bold 160px Georgia"
    ctx.textAlign = "left"
    ctx.fillText("\u201C", 110, 420)

    // Quote text (word wrap)
    ctx.fillStyle = "rgba(255,255,255,0.95)"
    ctx.font = "italic bold 44px Georgia, serif"
    ctx.textAlign = "center"
    const words = quote.text.split(" ")
    const lines: string[] = []
    let line = ""
    for (const word of words) {
      const testLine = line + word + " "
      if (ctx.measureText(testLine).width > 820 && line !== "") {
        lines.push(line.trim())
        line = word + " "
      } else {
        line = testLine
      }
    }
    lines.push(line.trim())

    const lineHeight = 58
    const totalTextH = lines.length * lineHeight
    const startY = cardY + (cardH - totalTextH) / 2 - 20
    lines.forEach((l, i) => {
      ctx.fillText(l, 540, startY + i * lineHeight)
    })

    // Author
    ctx.fillStyle = "rgba(255,255,255,0.6)"
    ctx.font = "500 34px Georgia, serif"
    ctx.textAlign = "center"
    ctx.fillText("\u2014 " + quote.author, 540, cardY + cardH - 60)

    // Category badge
    ctx.fillStyle = "rgba(255,255,255,0.15)"
    ctx.beginPath()
    ctx.roundRect(440, cardY + 30, 200, 50, 25)
    ctx.fill()
    ctx.fillStyle = "rgba(255,255,255,0.8)"
    ctx.font = "500 26px sans-serif"
    ctx.textAlign = "center"
    ctx.fillText(quote.category.toUpperCase(), 540, cardY + 64)

    // Watermark bottom
    ctx.fillStyle = "rgba(255,255,255,0.35)"
    ctx.font = "24px sans-serif"
    ctx.textAlign = "center"
    ctx.fillText("Generated by QuoteApp", 540, 1040)

    resolve(canvas.toDataURL("image/png"))
  })
}

export function ShareButtons({ quote, onShare }: ShareButtonsProps) {
  const [downloading, setDownloading] = useState(false)
  const [copied, setCopied] = useState(false)

  const handleDownload = async () => {
    setDownloading(true)
    try {
      const dataUrl = await drawQuoteImage(quote)
      const link = document.createElement("a")
      link.href = dataUrl
      link.download = `quoteapp-${quote.id}.png`
      link.click()
    } finally {
      setDownloading(false)
    }
  }

  const shareText = `"${quote.text}" — ${quote.author}\n\nShared via QuoteApp`
  const encodedText = encodeURIComponent(shareText)

  const shareLinks = [
    {
      label: "WhatsApp",
      href: `https://wa.me/?text=${encodedText}`,
      color: "bg-[#25D366] hover:bg-[#1ebe5d] text-white",
      icon: (
        <svg viewBox="0 0 24 24" fill="currentColor" className="h-4 w-4" aria-hidden="true">
          <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51a12.8 12.8 0 0 0-.57-.01c-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 0 1-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 0 1-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 0 1 2.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0 0 12.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 0 0 5.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 0 0-3.48-8.413Z" />
        </svg>
      ),
    },
    {
      label: "X",
      href: `https://twitter.com/intent/tweet?text=${encodedText}`,
      color: "bg-black hover:bg-neutral-800 text-white",
      icon: (
        <svg viewBox="0 0 24 24" fill="currentColor" className="h-4 w-4" aria-hidden="true">
          <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
        </svg>
      ),
    },
    {
      label: "Facebook",
      href: `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent("https://quoteapp.vercel.app")}&quote=${encodedText}`,
      color: "bg-[#1877F2] hover:bg-[#166fe5] text-white",
      icon: (
        <svg viewBox="0 0 24 24" fill="currentColor" className="h-4 w-4" aria-hidden="true">
          <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z" />
        </svg>
      ),
    },
  ]

  const manualSharePlatforms = [
    {
      label: "Instagram",
      color: "bg-gradient-to-br from-[#833AB4] via-[#FD1D1D] to-[#FCAF45] hover:opacity-90 text-white",
      icon: (
        <svg viewBox="0 0 24 24" fill="currentColor" className="h-4 w-4" aria-hidden="true">
          <path d="M12 0C8.74 0 8.333.015 7.053.072 5.775.132 4.905.333 4.14.63c-.789.306-1.459.717-2.126 1.384S.935 3.35.63 4.14C.333 4.905.131 5.775.072 7.053.012 8.333 0 8.74 0 12s.015 3.667.072 4.947c.06 1.277.261 2.148.558 2.913.306.788.717 1.459 1.384 2.126.667.666 1.336 1.079 2.126 1.384.766.296 1.636.499 2.913.558C8.333 23.988 8.74 24 12 24s3.667-.015 4.947-.072c1.277-.06 2.148-.262 2.913-.558.788-.306 1.459-.718 2.126-1.384.666-.667 1.079-1.335 1.384-2.126.296-.765.499-1.636.558-2.913.06-1.28.072-1.687.072-4.947s-.015-3.667-.072-4.947c-.06-1.277-.262-2.149-.558-2.913-.306-.789-.718-1.459-1.384-2.126C21.319 1.347 20.651.935 19.86.63c-.765-.297-1.636-.499-2.913-.558C15.667.012 15.26 0 12 0zm0 2.16c3.203 0 3.585.016 4.85.071 1.17.055 1.805.249 2.227.415.562.217.96.477 1.382.896.419.42.679.819.896 1.381.164.422.36 1.057.413 2.227.057 1.266.07 1.646.07 4.85s-.015 3.585-.074 4.85c-.061 1.17-.256 1.805-.421 2.227-.224.562-.479.96-.899 1.382-.419.419-.824.679-1.38.896-.42.164-1.065.36-2.235.413-1.274.057-1.649.07-4.859.07-3.211 0-3.586-.015-4.859-.074-1.171-.061-1.816-.256-2.236-.421-.569-.224-.96-.479-1.379-.899-.421-.419-.69-.824-.9-1.38-.165-.42-.359-1.065-.42-2.235-.045-1.26-.061-1.649-.061-4.844 0-3.196.016-3.586.061-4.861.061-1.17.255-1.814.42-2.234.21-.57.479-.96.9-1.381.419-.419.81-.689 1.379-.898.42-.166 1.051-.361 2.221-.421 1.275-.045 1.65-.06 4.859-.06l.045.03zm0 3.678c-3.405 0-6.162 2.76-6.162 6.162 0 3.405 2.76 6.162 6.162 6.162 3.405 0 6.162-2.76 6.162-6.162 0-3.405-2.76-6.162-6.162-6.162zM12 16c-2.21 0-4-1.79-4-4s1.79-4 4-4 4 1.79 4 4-1.79 4-4 4zm7.846-10.405c0 .795-.646 1.44-1.44 1.44-.795 0-1.44-.646-1.44-1.44 0-.794.646-1.439 1.44-1.439.793-.001 1.44.645 1.44 1.439z" />
        </svg>
      ),
    },
    {
      label: "TikTok",
      color: "bg-black hover:bg-neutral-800 text-white",
      icon: (
        <svg viewBox="0 0 24 24" fill="currentColor" className="h-4 w-4" aria-hidden="true">
          <path d="M12.525.02c1.31-.02 2.61-.01 3.91-.02.08 1.53.63 3.09 1.75 4.17 1.12 1.11 2.7 1.62 4.24 1.79v4.03c-1.44-.05-2.89-.35-4.2-.97-.57-.26-1.1-.59-1.62-.93-.01 2.92.01 5.84-.02 8.75-.08 1.4-.54 2.79-1.35 3.94-1.31 1.92-3.58 3.17-5.91 3.21-1.43.08-2.86-.31-4.08-1.03-2.02-1.19-3.44-3.37-3.65-5.71-.02-.5-.03-1-.01-1.49.18-1.9 1.12-3.72 2.58-4.96 1.66-1.44 3.98-2.13 6.15-1.72.02 1.48-.04 2.96-.04 4.44-.99-.32-2.15-.23-3.02.37-.63.41-1.11 1.04-1.36 1.75-.21.51-.15 1.07-.14 1.61.24 1.64 1.82 3.02 3.5 2.87 1.12-.01 2.19-.66 2.77-1.61.19-.33.4-.67.41-1.06.1-1.79.06-3.57.07-5.36.01-4.03-.01-8.05.02-12.07z" />
        </svg>
      ),
    },
  ]

  const handleCopyLink = async () => {
    await navigator.clipboard.writeText(shareText)
    setCopied(true)
    onShare?.()
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="w-full space-y-3">
      {/* Social share row */}
      <div className="flex gap-2">
        {shareLinks.map((link) => (
          <a
            key={link.label}
            href={link.href}
            target="_blank"
            rel="noopener noreferrer"
            onClick={() => onShare?.()}
            aria-label={`Share on ${link.label}`}
            className={`flex flex-1 items-center justify-center gap-1.5 rounded-2xl py-3 text-xs font-semibold transition-all duration-200 active:scale-95 font-sans ${link.color}`}
          >
            {link.icon}
            {link.label}
          </a>
        ))}
      </div>

      {/* Manual share platforms (Instagram, TikTok) with tooltip */}
      <div className="flex gap-2">
        {manualSharePlatforms.map((platform) => (
          <button
            key={platform.label}
            onClick={handleDownload}
            aria-label={`Download to share on ${platform.label}`}
            className={`group relative flex flex-1 items-center justify-center gap-1.5 rounded-2xl py-3 text-xs font-semibold transition-all duration-200 active:scale-95 font-sans ${platform.color}`}
          >
            {platform.icon}
            {platform.label}
            <span className="pointer-events-none absolute -top-10 left-1/2 -translate-x-1/2 whitespace-nowrap rounded-lg bg-black/90 px-3 py-1.5 text-xs text-white opacity-0 transition-opacity group-hover:opacity-100">
              Download to share
            </span>
          </button>
        ))}
      </div>

      {/* Download + Copy row */}
      <div className="flex gap-2">
        <button
          onClick={handleDownload}
          disabled={downloading}
          aria-label="Download quote as image"
          className="flex flex-1 items-center justify-center gap-2 rounded-2xl bg-secondary py-3 text-sm font-semibold text-secondary-foreground border border-border transition-all duration-200 active:scale-95 hover:bg-muted font-sans"
        >
          <Download className="h-4 w-4" aria-hidden="true" />
          {downloading ? "Generating..." : "Download"}
        </button>
        <button
          onClick={handleCopyLink}
          aria-label="Copy quote to clipboard"
          className="flex flex-1 items-center justify-center gap-2 rounded-2xl bg-secondary py-3 text-sm font-semibold text-secondary-foreground border border-border transition-all duration-200 active:scale-95 hover:bg-muted font-sans"
        >
          {copied ? (
            <Check className="h-4 w-4 text-emerald-400" aria-hidden="true" />
          ) : (
            <Share2 className="h-4 w-4" aria-hidden="true" />
          )}
          {copied ? "Copied!" : "Copy"}
        </button>
      </div>
    </div>
  )
}
